# Etapa 1: Build del frontend
FROM node:20-alpine AS builder

ARG VITE_API_URL
ARG VITE_APP_URL
ARG VITE_ADMIN_PASSWORD

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_ADMIN_PASSWORD=$VITE_ADMIN_PASSWORD

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
